### ISSUE TITLE
Import uhub/awesome-matlab items

### ISSUE THREAD

**Issue by egeerardyn** [mikecroucher/awesome-MATLAB#15]
I found another kickstart for an awesome MATLAB list at https://github.com/uhub/awesome-matlab

However, it seems to be abandoned and the structure could definitely use some tender love and care. Anyhow, I propose we salvage from that list whatever we can and incorporate it into this list.

**Comment by mikecroucher** [comment]
Someone from Mathworks pointed me to that one after I announced this list 

http://www.walkingrandomly.com/?p=5936#comments

I agree...taking things from that list and giving them some love would be a good idea. However, I have tried to ensure that I only include things that I personally know about. After all, if I don't know something personally, how can I say if it is awesome or not?

Looking at some other 'awesome' lists, I see that they can degenerate into simply HUGE lists of everything possible...which defeats the object.

We are already at risk of that here. There's stuff on our list that I don't think is awesome. However, someone else stepped up and said 'Well I do!' and that's enough for me until proven otherwise.

**Comment by gramian** [comment]
From a quick glance this list seems pretty focused on machine learning and dominated by links to github repos. I wouldn't rule out that it is automatically generated from github search results for certain keywords. Nonetheless, I will take a coarse look at the other list and include specific links I feel to be noteworthy.

**Comment by egeerardyn** [comment]
@mikecroucher I wholeheartedly agree with you: we have to be careful with what (not) to include. I'm not as strict to only include what I personally use, sometimes it's easy to see whether a resource is awesome or not. (Speaking of awesome: Michelle Hirsch is one of the awesome people of The MathWorks).

@gramian I do agree with your observation that that list could certainly be automatically generated as it is almost identical to what you get when search [MATLAB code sorted by rating](https://github.com/search?l=Matlab&o=desc&q=MATLAB&s=stars&type=Repositories&utf8=✓). I only see github links, so maybe it's more appropriate to use the updated view from GitHub rather than that outdated snapshot.
