### ISSUE TITLE
Discussion: Writing Fast MATLAB code link

### ISSUE THREAD

**Issue by mikecroucher** [mikecroucher/awesome-MATLAB#23]
Currently in the 'Tips and Tricks' section. The link is to http://www.csc.kth.se/utbildning/kth/kurser/DN2255/ndiff13/matopt.pdf

There is no text for why this link is awesome.

The pdf is rather old (2009). MATLAB has change a lot since then.

Should we remove this link?

**Comment by egeerardyn** [comment]
I would rather point towards http://www.mathworks.com/matlabcentral/fileexchange/5685-writing-fast-matlab-code (I suppose that link is more stable).

Personally, I think that it is a great resource. Sure, it is quite old and there have been many changes to MATLAB since (different JIT engine, for-looping are not as bad as back when that guide was written). But it touches very general topics on performance for MATLAB (vectorization, preallocation, use of profiler and mlint, ...) that are still very valid.

**Comment by gramian** [comment]
I would also keep it, but also use the fileexchange location. Most of it still applies nowadays as mentioned before.

**Comment by apjanke** [comment]
:+1: for keeping and updating maybe updating to the File Exchange path. The fundamentals still apply.
